spring.application.name=personal-finance-manager

## H2 database (solo desarrollo)
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
## Consola H2
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console


# JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

#shows sql in terminal
#spring.jpa.show-sql=true

#Disable show sql
spring.jpa.show-sql=false


# -----------------------
# ------Postgres---------
#BD Password PFCAdmin
spring.datasource.url=jdbc:postgresql://localhost:5432/pfm
spring.datasource.username=postgres
spring.datasource.password=PFMAdmin
spring.datasource.driver-class-name=org.postgresql.Driver

